// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RuntimeAgentOptionMetadata } from "./RuntimeAgentOptionMetadata";

export type AgentAiProviderInfo = { id: string, displayName: string, provider: string, api: string | null, baseUrl: string | null, apiKey: string | null, model: string | null, models: Array<RuntimeAgentOptionMetadata>, enabled: boolean, order: number, };
