// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type AstraConfig = { agent: string | null, model: string | null, effort: string | null, permissionMode: string | null, createdAt: number, updatedAt: number, };
